/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiWebSearchRouteImport } from './routes/api/web-search'
import { Route as ApiSessionsRouteImport } from './routes/api/sessions'
import { Route as ApiFetchUrlRouteImport } from './routes/api/fetch-url'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiSessionsIdRouteImport } from './routes/api/sessions.$id'
import { Route as ApiSessionsIdMessagesRouteImport } from './routes/api/sessions.$id.messages'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebSearchRoute = ApiWebSearchRouteImport.update({
  id: '/api/web-search',
  path: '/api/web-search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionsRoute = ApiSessionsRouteImport.update({
  id: '/api/sessions',
  path: '/api/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFetchUrlRoute = ApiFetchUrlRouteImport.update({
  id: '/api/fetch-url',
  path: '/api/fetch-url',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionsIdRoute = ApiSessionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiSessionsRoute,
} as any)
const ApiSessionsIdMessagesRoute = ApiSessionsIdMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => ApiSessionsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/fetch-url': typeof ApiFetchUrlRoute
  '/api/sessions': typeof ApiSessionsRouteWithChildren
  '/api/web-search': typeof ApiWebSearchRoute
  '/api/sessions/$id': typeof ApiSessionsIdRouteWithChildren
  '/api/sessions/$id/messages': typeof ApiSessionsIdMessagesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/fetch-url': typeof ApiFetchUrlRoute
  '/api/sessions': typeof ApiSessionsRouteWithChildren
  '/api/web-search': typeof ApiWebSearchRoute
  '/api/sessions/$id': typeof ApiSessionsIdRouteWithChildren
  '/api/sessions/$id/messages': typeof ApiSessionsIdMessagesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/fetch-url': typeof ApiFetchUrlRoute
  '/api/sessions': typeof ApiSessionsRouteWithChildren
  '/api/web-search': typeof ApiWebSearchRoute
  '/api/sessions/$id': typeof ApiSessionsIdRouteWithChildren
  '/api/sessions/$id/messages': typeof ApiSessionsIdMessagesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/chat'
    | '/api/fetch-url'
    | '/api/sessions'
    | '/api/web-search'
    | '/api/sessions/$id'
    | '/api/sessions/$id/messages'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/chat'
    | '/api/fetch-url'
    | '/api/sessions'
    | '/api/web-search'
    | '/api/sessions/$id'
    | '/api/sessions/$id/messages'
  id:
    | '__root__'
    | '/'
    | '/api/chat'
    | '/api/fetch-url'
    | '/api/sessions'
    | '/api/web-search'
    | '/api/sessions/$id'
    | '/api/sessions/$id/messages'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiFetchUrlRoute: typeof ApiFetchUrlRoute
  ApiSessionsRoute: typeof ApiSessionsRouteWithChildren
  ApiWebSearchRoute: typeof ApiWebSearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/web-search': {
      id: '/api/web-search'
      path: '/api/web-search'
      fullPath: '/api/web-search'
      preLoaderRoute: typeof ApiWebSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sessions': {
      id: '/api/sessions'
      path: '/api/sessions'
      fullPath: '/api/sessions'
      preLoaderRoute: typeof ApiSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/fetch-url': {
      id: '/api/fetch-url'
      path: '/api/fetch-url'
      fullPath: '/api/fetch-url'
      preLoaderRoute: typeof ApiFetchUrlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sessions/$id': {
      id: '/api/sessions/$id'
      path: '/$id'
      fullPath: '/api/sessions/$id'
      preLoaderRoute: typeof ApiSessionsIdRouteImport
      parentRoute: typeof ApiSessionsRoute
    }
    '/api/sessions/$id/messages': {
      id: '/api/sessions/$id/messages'
      path: '/messages'
      fullPath: '/api/sessions/$id/messages'
      preLoaderRoute: typeof ApiSessionsIdMessagesRouteImport
      parentRoute: typeof ApiSessionsIdRoute
    }
  }
}

interface ApiSessionsIdRouteChildren {
  ApiSessionsIdMessagesRoute: typeof ApiSessionsIdMessagesRoute
}

const ApiSessionsIdRouteChildren: ApiSessionsIdRouteChildren = {
  ApiSessionsIdMessagesRoute: ApiSessionsIdMessagesRoute,
}

const ApiSessionsIdRouteWithChildren = ApiSessionsIdRoute._addFileChildren(
  ApiSessionsIdRouteChildren,
)

interface ApiSessionsRouteChildren {
  ApiSessionsIdRoute: typeof ApiSessionsIdRouteWithChildren
}

const ApiSessionsRouteChildren: ApiSessionsRouteChildren = {
  ApiSessionsIdRoute: ApiSessionsIdRouteWithChildren,
}

const ApiSessionsRouteWithChildren = ApiSessionsRoute._addFileChildren(
  ApiSessionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiChatRoute: ApiChatRoute,
  ApiFetchUrlRoute: ApiFetchUrlRoute,
  ApiSessionsRoute: ApiSessionsRouteWithChildren,
  ApiWebSearchRoute: ApiWebSearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
